openstax/openstax-cms

.travis.yml

plus minor refactoring changes

include coveralls and use updated travis

---

books/migrations/0003_bookindex.py
books/models.py
pages/migrations/0024_auto_20160107_1338.py
pages/migrations/0025_auto_20160107_1341.py
pages/migrations/0026_auto_20160107_1342.py
pages/models.py

THIS MUST BE MERGED AFTER https://github.com/openstax/openstax-cms/pull/36

Book index

---

.travis.yml
api/tests.py
openstax/settings/local.py.travis
salesforce/tests.py

Will fix tests once Salesforce data is finished being updated

remove salesforce tests

---

api/views.py

Changes are temporary; stability improvements are being implemented.

remove salesforce from user api

---

allies/models.py
books/models.py
openstax/functions.py

At the very least, this makes the code more DRY - I think it will also reduce the number of API calls for the frontend as well, speeding up the site.

change image URL to MEDIA_URL

---

mail/views.py

Reverts openstax/openstax-cms#152

Revert "change to field for testing"

---

mail/views.py

Reverts openstax/openstax-cms#151

Revert "return json of message being sent to debug mail issue"

---

mail/views.py

This reverts commit 812aa78f2eeb8b35a59c7338fe75f992580d78f9.

Revert "change from address to users address, instead of noreply"

---

api/serializers.py
api/urls.py
api/views.py

implement Document api

---

openstax/settings/base.py
openstax/settings/local.py.example
requirements/base.txt

be sure to run `pip install -Ur requirements/base.txt`

Upgrade django storages

---

books/models.py

These are slipping through into the TOC displayed on the book page.

convert entities to unicode in TOC from archive

---

accounts/tests.py
openstax/settings/test.py

These should be encrypted in local.py.travis

Remove QA keys from test settings

---

README.md
requirements/base.txt

Requirements and README.md are updated to reflect the changes.

Requirements and Readme are updated.

---

openstax/api.py
openstax/functions.py
openstax/settings/base.py
requirements/base.txt

Adds flags to django-admin dashboard, that are toggle-able filters to enable/disable features.

Implementing Flags

---

openstax/api.py
openstax/urls.py

This is a little messy with comments - but I wanted to document what I am doing and found pretty well.
I expect this will be fixed in a future release of Wagtail - and we can remove this code then.

Monkey patch for Wagtail upgrade that broke page drawer

---

errata/models.py

Customer will receive customized email body depending on what month the submission was created.

updated submission received email

---

errata/models.py

The reviewed/completed errata email will now be more clear about errata change schedule.

Changed reviewed/approved errata email

---

openstax/api.py
openstax/settings/base.py
openstax/urls.py

Reverts openstax/openstax-cms#880

Revert "revert wagtail admin api override (fixed pages drawer menu)"

---

errata/admin.py

modifying permissions to errata and reorganizing field display a bit.

Display errata submitter name to sme if faculty

---

errata/admin.py

I've done this in an attempt to get the user_faculty_status property in the model to show up in the exported CSV

dehydrate faculty status field

---

openstax/settings/base.py

Reverts openstax/openstax-cms#907

Revert "Add logging for scout APM"

---

errata/static/errata/errata-admin-ui.js

this controls the save button updating to let the user know when an email is being sent.

adding partner product to javascript

---

.travis.yml
README.md
admin_templates/templates/wagtailadmin/login.html
requirements/base.txt
salesforce/tests.py

This might need to be released by itself since it involves updating Python to 3.6 or above. Tested using Python 3.8.

Django 3.0 Upgrade - think before merging

---

.travis.yml
README.md
admin_templates/templates/wagtailadmin/login.html
requirements/base.txt
salesforce/tests.py

Reverts openstax/openstax-cms#993 until servers are upgraded to 3.6+

Revert "Django 3.0 Upgrade - think before merging"

---

books/models.py

Updating the CMS options to be more descriptive. 
@RoyEJohnson, if possible, let's try to get this done by code freeze on Friday.

Add more descriptive text to book states

---

errata/admin.py

added "additional_location_information" field to list of fields  pulled into errata csv  export

Adding field to errata export

---

admin_templates/templates/wagtailadmin/login.html
openstax/settings/local.py.example

Updating the wagtail admin login page to work with the upgraded wagtail version.
Also adding the DEBUG flag to the example local.py file (so you can login locally and see all the lovely error messages).

Update wagtail admin login

---

books/models.py

Modified salesforce field labels

---

errata/admin.py

Reverts openstax/openstax-cms#1174

Revert "Update admin.py"

---

pages/static/wagtail_hooks/css/page_wagtail_hooks.css
pages/wagtail_hooks.py

Internal Link option is hidden on Rich Text editor

---

openstax/settings/base.py

Reverts openstax/openstax-cms#1184

Revert "move cors config to cms"

---

openstax/settings/base.py
requirements/base.txt

Reverts openstax/openstax-cms#1181

Revert "add cors allowed hosts for local development"

---

salesforce/management/commands/update_review_faculty_status.py

get_user_info returns False if the user id is not found.

Correctly deal with user set to False

---

salesforce/views.py

`/apps/cms/api/salesforce/schools?search=rice`

add search filtering to schools endpoint

---

openstax/settings/base.py
requirements/production.txt

All of these seem to be unused

Removed South config, and django-redis and elasticsearch pip packages

---

codecov.yml
snippets/models.py

Added subject name to subject categories listing

---

openstax/settings/base.py
requirements/base.txt
requirements/production.txt

Added CRONJOBS and some configuration variables
Also added uwsgi as a prod requirement because why not

Re-added django-crontab

---

openstax/settings/base.py

This command will be fixed with #1284

remove adopters update from cron

---

salesforce/management/commands/update_resource_downloads.py

[Should resolve this error: https://sentry.io/organizations/openstax/issues/3735948785](https://github.com/openstax/openstax-cms/pull/1363)

only upload book data if the resource has a salesforce abbr

---

books/tests.py
books/views.py

Fixes Sentry [OPENSTAX-CMS-AD](https://sentry.io/organizations/openstax/issues/3510094535/?project=5594444)

Add check on queryset for Resources

---

snippets/views.py

Change in release-6.6.0 to sort subjects added to development branch

subject sort in release added to development

---

Dockerfile
README.md
docker-compose.override.yml
docker/start
openstax/settings/docker.py
requirements/dev.txt

- update versions in readme
- update postgres and python versions in docker configs
- rejigger docker build so that any code change doesn't bust the build cache
- add missing cors middleware package
- copied a few required configs from local.example to docker settings

update readme versions and docker configs

---

salesforce/management/commands/update_opportunities.py

These fields are slated for removal, so getting this put up before it causes a problem.

remove student numbers from opp query

---

.github/workflows/tests.yml

As suggested in PR 1458 by cclauss

Updated packages for Github Actions

---

docker-compose.override.yml

Fix for docker on new macs

---

errata/admin.py
requirements/base.txt

This handles all dependabot alerts + some other upgrades

security and functionality upgrades

---

requirements/base.txt

this takes care of currently open dependabot security alerts

security updates

---

api/views.py

https://openstax.slack.com/archives/C07K4CU96N6/p1729532827428759

remove tutor from the errata FE list

---

redirects/templates/wagtailredirects/add.html

To fix: https://openstax.sentry.io/issues/6028418477/?environment=prod&project=5594444&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=7d&stream_index=1

update redirect add template with new field format

---

wagtailimportexport/templates/wagtailimportexport/export-page.html
wagtailimportexport/templates/wagtailimportexport/import-page.html

I don't think will fix the tool, but it's an error.

update deprecated fields

---

openstax/urls.py

See: https://openstax.slack.com/archives/C6NRD0CCQ/p1729272684134509
"fixes": https://openstax.sentry.io/issues/5227998469/?environment=prod&project=5594444&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2Cmedium%5D&referrer=issue-stream&sort=date&statsPeriod=7d&stream_index=2

remove unused paths for images

---

books/views.py
news/models.py
salesforce/management/commands/update_opportunities.py

For: https://openstax.slack.com/archives/C69BU01RC/p1732573840189719

only fetch active book adoptions

---

books/models.py

see: https://openstax.slack.com/archives/C8V1XET1R/p1729099577468089?thread_ts=1729007888.171019&cid=C8V1XET1R

stop generating the cnx id for books

---

snippets/views.py

https://openstax.atlassian.net/browse/CORE-768
Adds a locale filter to the snippet roles. Defaults to English to keep backward compatibility.

add locale filter to snippet roles

---

fixtures/vcr_cassettes/partners.yaml
salesforce/management/commands/update_partners.py

https://openstax.slack.com/archives/C07K2UT894Z/p1740695646750129

only fetch full partners from SF
