- pages/migrations/0007_auto_20151216_1150.py
- pages/migrations/0008_homepage_intro_image.py
- pages/migrations/0009_homepage_page_header.py
- pages/migrations/0010_homepage_introduction.py
- pages/models.py
This should help dictate how future pages will be created (one per common template - not necessarily one per template delivered). We want to keep all pages code here, and keep this model as DRY as possible in my opinion.
> Restructure Page subclasses to include descriptive API fields

- api/tests.py
- api/urls.py
- openstax/urls.py
- pages/tests/tests.py
Returns uploaded file paths along with other fields. Note that v1 api is still available.
> Image api v0

- accounts/backend.py
Caused by changes to the urllib module between python 2.7 and 3.5. 
https://docs.python.org/2.7/library/urllib.html#urllib.urlopen
> fixing urllib import error

- accounts/salesforce.py
- accounts/tests.py
- api/views.py
This will allow for queries to the user api link, even if salesforce fails.
> update Salesforce class to catch errors during initiation. 

- openstax/settings/base.py
- openstax/settings/local.py.example
We no longer need this, since we moved the api and frontend to the same url.
> remove domain specific cookie settings

- accounts/tests.py
- accounts/utils.py
- api/serializers.py
- api/tests.py
- api/views.py
- salesforce/tests.py
- ``/api/user/`` update adds ``accounts_id`` to queries.
- ``accounts.utils.create_user`` update changes the return value to a ``User`` object.
> /api/user/ and accounts.utils.create_user updates

- openstax/urls.py
- openstax/views.py
This is causing an issue with custom redirects, where they don't work while Debug=False.
Removing so it doesn't break the next deploy.
> remove custom 404 handler

- errata/serializers.py
- errata/views.py
FE should add these filters to the API endpoint as needed, so that all errata is accessible at the detail page.
> Remove errata API filters

- requirements/base.txt
- wagtailimportexport/__init__.py
- wagtailimportexport/admin_urls.py
- wagtailimportexport/apps.py
- wagtailimportexport/compat.py
- wagtailimportexport/exporting.py
- wagtailimportexport/forms.py
- wagtailimportexport/importing.py
- wagtailimportexport/templates/wagtailimportexport/export_to_file.html
- wagtailimportexport/templates/wagtailimportexport/import_from_api.html
- wagtailimportexport/templates/wagtailimportexport/import_from_file.html
- wagtailimportexport/templates/wagtailimportexport/index.html
- wagtailimportexport/urls.py
- wagtailimportexport/views.py
- wagtailimportexport/wagtail_hooks.py
I've submitted a PR to the import-export project. Once merged, we can go back to using Pypy... until then, this allows using it by ID.
> move wagtailimportexport to project to fix a bug

- openstax/urls.py
Both `/api/` and `/apps/cms/api/` should still resolve to the same endpoint.
> Alias API URLs to /apps/cms/api/

- Dockerfile
- README.md
- docker-compose.override.yml
- docker-compose.yml
- docker/bash
- docker/entrypoint
- docker/start
- openstax/settings/docker.py
I was trying to poke around with something on this app, but was unable to install the dependencies for it (got some lxml error with Python 3.7).  Instead of trying to fix my mac's environment, gave a shot at adding docker for local development, which is this PR.  @TomWoodward I started from your docker stuff on tutor-server.  I've never dockerized something before so I'd appreciate you taking a look and telling me where I'm a crazy man. 
Code is mounted in the container so you can develop on your local (host) machine, and Django auto reloads the changes.
Updated the README with how to use docker for the CMS.
cc @mwharrison
> add docker for local development

- .travis.yml
Should save travis from doing pip install every time.  Build time before was 5-7 mins.
First run of travis (pip was not yet cached) was 6 mins 13 seconds.
Second run (pip was cached) was 4 mins 34 seconds.
> cache pip install on travis to speed up builds

- Dockerfile
- books/tests.py
- books/urls.py
- mail/tests.py
- mail/urls.py
- news/tests.py
- news/urls.py
- openstax/settings/base.py
- openstax/urls.py
- oxauth/urls.py
- pages/tests.py
- pages/urls.py
- shared/test_utilities.py
- shared/tests.py
While investigating adding OSWeb into the Unified Cloudfront distribution, I spent some time looking at the requests in the Network tab of the Chrome inspector.  I noticed that there were lots of 301 redirects to the original request path with a trailing slash added.  Of 93 requests made to load https://openstax.org, 21 were redirects of this form.  These requests mostly took 50-150ms each.  Some are likely prefetching of content, so maybe it isn't directly seen by users, but still these are requests we shouldn't have to make (network traffic we shouldn't be hoisting on the client's device).
Here's an example of one request:
1. Request made to `https://[some-os-web-domain]/apps/cms/api/books?format=json`
2. 301 redirects to `/apps/cms/api/books/?format=json` (trailing slash added)
3. 302 …
> Make trailing slashes optional without using redirects

- books/views.py
- news/models.py
- news/views.py
- openstax/settings/base.py
- pages/views.py
- shared/tests.py
Setting `WAGTAIL_APPEND_SLASH=False` was supposed to allow wagtail endpoints to handle URLs without and without trailing slashes, but maybe because of how we were building our own `/api/...` endpoints using wagtail it wasn't working.
So we revert that part of https://github.com/openstax/openstax-cms/pull/753
> Undo WAGTAIL_APPEND_SLASH=False

- openstax/urls.py
I think changing the url for now to avoid collisions and identify where oauth is still getting used on the site is the best way to get this ported.
> change /accounts to /auth

- Dockerfile
- accounts/tests.py
- accounts/urls.py
- accounts/views.py
- openstax/settings/base.py
- openstax/urls.py
- oxauth/tests.py
- oxauth/urls.py
- oxauth/views.py
Instead of redirecting login and logout to a full Accounts URL, redirect to `/accounts/...`.  In a CloudFront deployment, such a redirect will be routed to the desired Accounts instance with the benefit that the URL in the browser will keep the same top-level domain, e.g. https://openstax.org/accounts/login.  In a local or test environment (which obviously doesn't have CloudFront), there is a new `accounts` action and URL to do the full domain redirect as was done previously.
This PR makes the Accounts URL behavior match that in REX.
> use cloudfront proxied accounts

- openstax/settings/base.py
This was not implemented on the FE - and to do so means modifying the PI code, which is a bad idea. So we're going to remove this to alliviate confusion.
> Remove pulse insight feature flag.

- openstax/settings/base.py
See this for details: https://stackoverflow.com/questions/46538682/wagtail-admin-icons-disappear-when-running-collectstatic-and-putting-everything
> Add AWS header setting

- errata/admin.py
the drop-down wasn't removing the mass-mark options as it should have been. Testing shows it is now working as intended.
> applying fix

- errata/admin.py
this was preventing the detail field from being copied over when saving an erratum as a new one (copying it)
> removing detail field from read-only section for Editorial Vendors group

- errata/models.py
This case isn't used anymore and can be removed from code as well.
> Removing "Completed and Approved" email case

- openstax/settings/base.py
The current count is not accurate. It is displaying zero for all files. While the cause of the zero count is not currently know, it was decided to turn the count display off because of an [issue in Wagtail](https://github.com/wagtail/wagtail/issues/1162) where StreamFields are not included in the count. Some of our documents and images are in StreamFields. We will revisit this once Wagtail has added StreamFields to the count.
> Set file usage flag to False

- errata/models.py
- global_settings/functions.py
- global_settings/wagtail_hooks.py
we were invalidating the cache after a page save - we also need to do it when a piece of errata is saved
> invalidate cloudfront cache after errata save

- openstax/settings/base.py
- openstax/settings/dev.py
- openstax/settings/prod.py
- openstax/settings/qa.py
- openstax/settings/staging.py
Local environments are currently reporting to Sentry. This is not useful and results in lots of local errors being reported. Moving them so they only work on dev/qa/staging/prod.
> move sentry configs to env settings

- redirects/management/commands/check_redirects.py
Timeout now has 10 seconds for connection and 10 seconds for data load. This solved all of the 429 errors from Youtube.  Using certifi to verify certificates. Certifi uses Mozilla's pem file which lists trusted CAs. Since there are still some odd errors from the URL we redirect to being redirected as well, I added the exception to the redirect email sent to the content team. This might or might not be helpful. I left the dev email so I can compare what happens in Feb. when the report runs in production.
> Modified timeout and added certifi to eliminate SSL errors

- news/models.py
News API no longer has articles:` [domain]/apps/cms/api/v2/pages/openstax-news/?format=json`
News Article API has `blog_blurb` field added. Image alt text is available using `featured_image_alt_text`
Example URL: `[domain]/apps/cms/api/v2/pages/?type=news.newsArticle&fields=title,id,article_image,featured_image_alt_text,heading,subheading,body_blurb&limit=20`
> Removed articles from news page, added blog_blurb field to news article

- books/models.py
Google is complaining that errata is in the sitemap and we recently blocked it in robots.txt.
> Removed errata links from sitemap

- openstax/api.py
API now adds height and width to promote_image field
```
"promote_image": {
"id": 907,
"meta": {
"width": 1200,
"height": 628,
"type": "wagtailimages.Image",
"detail_url": "http://openstax.org/apps/cms/api/v2/images/907/",
"download_url": "/media/original_images/biology-2e.png"
},
"title": "biology-2e.png"
},
```
> Added height and width to promo image

- requirements/base.txt
Getting some errors on images with GIFs. This is the ImageMagik python bindings - some Github issues appeared to fix the issue by upgrading.
> Upgrade wand package

- openstax/settings/base.py
@RoyEJohnson you can query for this flag here: /apps/cms/api/flags?flag=enable_my_openstax
It will return a value of True (show the my openstax links and such) or False (don't).
Feature flags can be modified in the admin, here: http://dev.openstax.org/django-admin/flags/flagstate/
This can be modified if you think it'd work better some other way - just let me know!
> add feature flag for my openstax

- books/models.py
-  There should be only one Spanish Errata Content snippet in the CMS. The selected book state does not matter.
-  All Spanish books will display the one Spanish Errata Content text
-  English books will have a different Errata Content snippets based on book state.
> Use same errata content snippet for all Spanish books

- books/models.py
- books/tests.py
- errata/tests.py
If an English book fields are edited, all of the English books will get updated.  Same for Spanish. They should not mix.
> Update partner fields based on locale

- api/tests.py
- api/views.py
Switched back to using `and`. Using `or` was causing both options to remain displayed.
> Fixed bad logic and removed print stmt from test

- openstax/settings/base.py
Another parameter that had a different name for some reason
> Fix mapbox token parameter name

- healthcheck/filter.py
- openstax/settings/base.py
To reduce log spam, since this path is called every 5 seconds by the ELB
> Filter successful /ping requests from Django logs

- openstax/settings/base.py
- openstax/urls.py
I think we are somewhat overcomplicating things by using accounts to login to the Django admin since we have so few people accessing it. 
The auth code is still there - so when we add more fine grained permissions into accounts we can reimplement this but for now, let's just use the django auth mechanism for logging into the admin.
> use django auth for login

- openstax/settings/base.py
No idea why this started being required now, but Nathan reported he couldn't view an uploaded image.
The image was missing the public read ACL in S3, which this setting seems to fix.
> Set S3 default ACL to public-read

- backup/README.md
- openstax/settings/base.py
- requirements/base.txt
[Documentation](https://django-dbbackup.readthedocs.io/en/master/installation.html) for DBBackup
Can be used to create a database backup file that can be copied using bit-deployment to another location.
> Added django-dbbackup to install

- docker-compose.override.yml
[According to Colby](https://openstax.slack.com/archives/C0LA54Q5C/p1692813178119899?thread_ts=1692811204.056329&cid=C0LA54Q5C) this works (I have no way to test it and GH actions still [does not support ARM on their CI](https://github.com/actions/runner-images/issues/5631)):
Problem on Mac M1:
* The application docker container fails on gcc compilation step on Mac M1/M2 laptops on build.
* When forcing whole docker compose to use AMD64 architecture, the Postgres container will not work in daemon mode. So Wagtail cannot be started.
Solution is to run both containers in a mixed architecture on ARM:
* Force AMD64 architecture on the application container (will be emulated internally on Docker with QEMU)
* and let Postgres container run in the architecture in which the docker host is running …
> force specific platform only on the Docker app container (fix for Mac M1)

- books/tests.py
- books/views.py
- fixtures/vcr_cassettes/retired_book.yaml
Removed check for retired books, but left the one for resources. REX uses the retired books API.
> Return NotFound error with message for retired books

- books/models.py
- news/models.py
- pages/models.py
https://openstax.atlassian.net/browse/DISCO-436
mostly i'm doing this for the correct html_url on blog posts for the impact stories
there were some places in the code that were customizing their urls with only the get_sitemap_urls override, but the documentation recommends using get_url_parts. the url generated by get_url_parts also seems to be used by the sitemap code, so in some place i just removed the sitemap override with the url parts override
removed new subjects feature flag
fixed flex page urls (they were inheriting the `/` override from rootpage)
marked impact stories and deprecated book index as non-navigable by returning none from url_parts, as suggested in the documentation. weirdly this doesn't omit it from the sitemap, so you need to override that too or None appears in the …
> Url jiggering

- openstax/api.py
- pages/models.py
- pages/templates/preview.html
https://openstax.atlassian.net/browse/DISCO-441
the https://github.com/torchbox/wagtail-headless-preview project ended up not really working for me here, it had a kind of excessively complicated system for actually hooking up the preview button, didn't work for UIs that loaded multiple pages. 
in the end it really wasn't that complicated to just hook it up without a library
> Hook up preview

- openstax/settings/base.py
- salesforce/management/commands/update_opportunities.py
This seems to be the way to handle the [2k record limit](https://help.salesforce.com/s/articleView?id=000386264&type=1).
[Simple Salesforce documentation](https://github.com/simple-salesforce/simple-salesforce?tab=readme-ov-file#queries)
> use query_all to get all records

- openstax/settings/base.py
it takes a lot of API calls and can always be run manually
> only run the adoption update on prod

- salesforce/management/commands/sync_thank_you_notes.py
We (Data Intel) decided that thank you notes are not very useful if they don't tie back to a school or have a meaningful message. This is to cull those out or assign them to a general school.
**Q: should we keep them in the CMS if they don't meet quality standards?**
> handle non-useful thank you notes
